export const profileId = '11111111-1111-4111-8111-111111111111'

export const profile = {
  highlights: {
    favoriteCategory: 'Электроника',
    leastExpensivePurchase: null,
    leastExpensiveSale: null,
    mostExpensivePurchase: null,
    mostExpensiveSale: null,
  },
  id: profileId,
  joinedAt: '2020-01-01T00:00:00Z',
  name: 'Тестовый профиль',
  ownAds: [{
    adId: 'own-ad-1',
    category: 'Электроника',
    city: 'Краснодар',
    contactsCount: 4,
    favoritesCount: 7,
    isArchived: false,
    isSold: false,
    price: 25_000,
    publishedAt: '2026-02-01T10:00:00Z',
    title: 'Игровая консоль',
    viewCount: 42,
  }],
  purchases: [],
  sales: [],
  stats: {
    averageRating: null,
    chatsCount: 2,
    likes: 3,
    purchasesCount: 1,
    reviewsCount: 0,
    salesCount: 1,
    totalEarned: 2_000,
    totalSpent: 1_000,
    totalViewCount: 10,
  },
  views: [{
    adId: 'view-ad-1',
    category: 'Электроника',
    favoritedAt: '2026-03-10T11:00:00Z',
    isFavorite: true,
    isPurchased: false,
    price: 12_990,
    title: 'Беспроводные наушники',
    viewCount: 8,
    viewedAt: [{ time: '2026-03-10T10:00:00Z', type: 'watch' }],
  }],
}

export const recap = {
  achievements: [],
  activity_days: 4,
  comparison: {
    categories: [{ absolute_change: 12, category: 'Электроника', current_score: 22, is_new: false, percent_change: 120, previous_score: 10 }],
    current_year: 2026,
    message: 'В этом году вы стали активнее.',
    new_interests: [],
    previous_year: 2025,
    sales_revenue: { absolute_change: 1_000, current: 2_000, percent_change: 100, previous: 1_000 },
    spending: { absolute_change: 500, current: 1_000, percent_change: 100, previous: 500 },
    status: 'available',
  },
  cards: [
    {
      description: 'История тестового профиля.',
      eyebrow: 'Итоги 2026',
      id: 'year_overview',
      kind: 'overview',
      presentation: { icon: 'sparkles', layout: 'hero', theme: 'avito-purple' },
      reason: 'Тест',
      shareable: true,
      title: 'Ваш год на Авито',
      value: '2026',
    },
    {
      description: 'Выберите миссию и продолжите историю в следующем году.',
      eyebrow: 'До встречи',
      id: 'year_final',
      kind: 'final',
      presentation: { icon: 'sparkles', layout: 'hero', theme: 'avito-blue' },
      reason: 'Финальный экран итогов.',
      shareable: true,
      title: 'Продолжение следует',
    },
  ],
  generated_at: '2026-08-08T00:00:00Z',
  forecast: {
    likely_categories: [{ category: 'Электроника', expected_score: 25 }],
    method: 'linear_year_over_year',
    sales_revenue: { expected: 3_000, max: 3_500, min: 2_500 },
    spending: { expected: 1_500, max: 2_000, min: 1_000 },
    year: 2027,
  },
  id: 'recap-e2e',
  summary: {
    buyer: {
      avito_delivery_purchases: 0,
      chats_count: 2,
      favorites_count: 3,
      has_data: true,
      purchases_count: 1,
      total_views: 10,
      viewed_ads_count: 1,
    },
    combined: { categories_count: 1, deals_count: 2, has_buyer_data: true, has_seller_data: true },
    description: 'История тестового профиля.',
    headline: 'Ваш год на Авито',
    seller: {
      active_listings: 0,
      archived_listings: 1,
      average_rating: null,
      contacts_received: 0,
      favorites_received: 0,
      has_data: true,
      likes_received: 0,
      listing_views: 5,
      listings_count: 1,
      reviews_count: 0,
      sales_count: 1,
    },
  },
  top_categories: [],
  total_favorites: 3,
  total_messages: 2,
  total_purchases: 1,
  total_sales: 1,
  total_views: 10,
  user_id: profileId,
  year: 2026,
}

export const missionOverview = {
  options: [
    {
      code: 'sell_three_items',
      cta: { action: 'create_listing', label: 'Разместить объявление' },
      description: 'Помогите трём вещам найти новых владельцев.',
      icon: 'recycle',
      target: 3,
      theme: 'avito-green',
      title: 'Продать три ненужные вещи',
    },
    {
      code: 'buy_from_favorites',
      cta: { action: 'open_favorites', label: 'Открыть избранное' },
      description: 'Превратите одну сохранённую находку в покупку.',
      icon: 'heart',
      target: 1,
      theme: 'avito-red',
      title: 'Завершить покупку из избранного',
    },
    {
      code: 'try_avito_delivery',
      cta: { action: 'open_delivery_items', label: 'Найти товары с Доставкой' },
      description: 'Совершите одну покупку с Авито Доставкой.',
      icon: 'delivery',
      target: 1,
      theme: 'avito-blue',
      title: 'Попробовать Авито Доставку',
    },
  ],
  selected: null,
}
