export const profileId = '11111111-1111-4111-8111-111111111111'

export const profile = {
  highlights: {
    favoriteCategory: 'Электроника',
    leastExpensivePurchase: null,
    leastExpensiveSale: null,
    mostExpensivePurchase: null,
    mostExpensiveSale: null,
  },
  id: profileId,
  joinedAt: '2020-01-01T00:00:00Z',
  name: 'Тестовый профиль',
  ownAds: [{
    adId: 'own-ad-1',
    category: 'Электроника',
    city: 'Краснодар',
    contactsCount: 4,
    favoritesCount: 7,
    isArchived: false,
    isSold: false,
    price: 25_000,
    publishedAt: '2026-02-01T10:00:00Z',
    title: 'Игровая консоль',
    viewCount: 42,
  }],
  purchases: [],
  sales: [],
  stats: {
    averageRating: null,
    chatsCount: 2,
    likes: 3,
    purchasesCount: 1,
    reviewsCount: 0,
    salesCount: 1,
    totalEarned: 2_000,
    totalSpent: 1_000,
    totalViewCount: 10,
  },
  views: [{
    adId: 'view-ad-1',
    category: 'Электроника',
    favoritedAt: '2026-03-10T11:00:00Z',
    isFavorite: true,
    isPurchased: false,
    price: 12_990,
    title: 'Беспроводные наушники',
    viewCount: 8,
    viewedAt: [{ time: '2026-03-10T10:00:00Z', type: 'watch' }],
  }],
}

export const recap = {
  achievements: [],
  activity_days: 4,
  cards: [
    {
      description: 'История тестового профиля.',
      eyebrow: 'Итоги 2026',
      id: 'year_overview',
      kind: 'overview',
      presentation: { icon: 'sparkles', layout: 'hero', theme: 'avito-purple' },
      reason: 'Тест',
      shareable: true,
      title: 'Ваш год на Авито',
      value: '2026',
    },
  ],
  generated_at: '2026-08-08T00:00:00Z',
  id: 'recap-e2e',
  summary: {
    buyer: {
      avito_delivery_purchases: 0,
      chats_count: 2,
      favorites_count: 3,
      has_data: true,
      purchases_count: 1,
      total_views: 10,
      viewed_ads_count: 1,
    },
    combined: { categories_count: 1, deals_count: 2, has_buyer_data: true, has_seller_data: true },
    description: 'История тестового профиля.',
    headline: 'Ваш год на Авито',
    seller: {
      active_listings: 0,
      archived_listings: 1,
      average_rating: null,
      contacts_received: 0,
      favorites_received: 0,
      has_data: true,
      likes_received: 0,
      listing_views: 5,
      listings_count: 1,
      reviews_count: 0,
      sales_count: 1,
    },
  },
  top_categories: [],
  total_favorites: 3,
  total_messages: 2,
  total_purchases: 1,
  total_sales: 1,
  total_views: 10,
  user_id: profileId,
  year: 2026,
}
