import { createMockProfileResponse } from '@/constants/createMockProfileResponse'
import type { CreateProfileRequest } from '@/types/profileRequest.type'
import type { GetProfilesResponse } from '@/types/profileResponse.type'

export const TEST_PROFILE_CREATE_REQUESTS: CreateProfileRequest[] = [
  {
    name: 'Анна Смирнова',
    joinedAt: '2018-04-14',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    likes: 148,
    chatsCount: 43,
    views: [
      {
        title: 'Смартфон',
        category: 'Электроника',
        subcategory: 'Смартфоны',
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=200&q=80',
        price: 118000,
        viewCount: 7,
        lastViewedAt: '2026-03-12T14:10:00',
        isFavorite: true,
        favoritedAt: '2026-03-10T18:20:00',
        isPurchased: true,
        purchasedAt: '2026-03-12T14:10:00',
      },
      {
        title: 'Наушники',
        category: 'Электроника',
        subcategory: 'Аудио',
        price: 12990,
        viewCount: 3,
        lastViewedAt: '2026-05-04T16:45:00',
        isFavorite: false,
        isPurchased: true,
        purchasedAt: '2026-05-04T16:45:00',
      },
      {
        title: 'Чехол для телефона',
        category: 'Аксессуары',
        price: 490,
        viewCount: 2,
        lastViewedAt: '2026-01-17T13:30:00',
        isFavorite: true,
        favoritedAt: '2026-01-15T11:05:00',
        isPurchased: true,
        purchasedAt: '2026-01-17T13:30:00',
      },
    ],
    ownAds: [
      {
        title: 'Планшет',
        category: 'Электроника',
        subcategory: 'Планшеты',
        price: 28500,
        viewCount: 214,
        isArchived: true,
        isSold: true,
        soldAt: '2026-02-20',
        review: { comment: 'Планшет в отличном состоянии, всё как в описании.', rating: 5, createdAt: '2026-02-21' },
      },
      {
        title: 'Кресло',
        category: 'Для дома',
        subcategory: 'Мебель',
        price: 7500,
        viewCount: 86,
        isArchived: true,
        isSold: true,
        soldAt: '2026-06-18',
      },
    ],
  },
  {
    name: 'Михаил Орлов',
    joinedAt: '2021-09-03',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    likes: 86,
    chatsCount: 51,
    views: [
      {
        title: 'Акустическая гитара',
        category: 'Хобби и отдых',
        subcategory: 'Музыкальные инструменты',
        price: 64900,
        viewCount: 11,
        lastViewedAt: '2026-05-21T19:20:00',
        isFavorite: true,
        favoritedAt: '2026-05-12T12:10:00',
        isPurchased: true,
        purchasedAt: '2026-05-21T19:20:00',
      },
      {
        title: 'Велосипедный шлем',
        category: 'Хобби и отдых',
        subcategory: 'Спорт',
        price: 5400,
        viewCount: 5,
        lastViewedAt: '2026-04-02T16:05:00',
        isFavorite: false,
        isPurchased: true,
        purchasedAt: '2026-04-02T16:05:00',
      },
      {
        title: 'Комплект струн',
        category: 'Хобби и отдых',
        subcategory: 'Музыкальные инструменты',
        price: 850,
        viewCount: 2,
        lastViewedAt: '2026-02-06T18:00:00',
        isFavorite: false,
        isPurchased: true,
        purchasedAt: '2026-02-06T18:00:00',
      },
    ],
    ownAds: [
      {
        title: 'Игровая консоль',
        category: 'Электроника',
        subcategory: 'Игровые приставки',
        price: 32000,
        viewCount: 326,
        isArchived: true,
        isSold: true,
        soldAt: '2026-03-04',
        review: { comment: 'Быстро договорились, всё работает.', rating: 5, createdAt: '2026-03-05' },
      },
      {
        title: 'Сноуборд',
        category: 'Хобби и отдых',
        subcategory: 'Спорт',
        price: 18500,
        viewCount: 189,
        isArchived: true,
        isSold: true,
        soldAt: '2026-01-26',
      },
    ],
  },
  {
    name: 'Елена Коваль',
    joinedAt: '2016-11-28',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    likes: 219,
    chatsCount: 27,
    views: [
      {
        title: 'Робот-пылесос',
        category: 'Для дома и дачи',
        subcategory: 'Бытовая техника',
        price: 54990,
        viewCount: 9,
        lastViewedAt: '2026-04-09T17:30:00',
        isFavorite: true,
        favoritedAt: '2026-04-01T10:15:00',
        isPurchased: true,
        purchasedAt: '2026-04-09T17:30:00',
      },
      {
        title: 'Торшер',
        category: 'Для дома и дачи',
        subcategory: 'Мебель и интерьер',
        price: 8990,
        viewCount: 4,
        lastViewedAt: '2026-05-28T20:10:00',
        isFavorite: false,
        isPurchased: true,
        purchasedAt: '2026-05-28T20:10:00',
      },
      {
        title: 'Набор полотенец',
        category: 'Для дома и дачи',
        subcategory: 'Текстиль',
        price: 1290,
        viewCount: 3,
        lastViewedAt: '2026-07-02T14:05:00',
        isFavorite: true,
        favoritedAt: '2026-06-25T18:00:00',
        isPurchased: true,
        purchasedAt: '2026-07-02T14:05:00',
      },
    ],
    ownAds: [
      {
        title: 'Детская кроватка',
        category: 'Товары для детей',
        subcategory: 'Детская мебель',
        price: 11200,
        viewCount: 164,
        isArchived: true,
        isSold: true,
        soldAt: '2026-02-14',
      },
      {
        title: 'Кофемашина',
        category: 'Для дома и дачи',
        subcategory: 'Бытовая техника',
        price: 19700,
        viewCount: 241,
        isArchived: true,
        isSold: true,
        soldAt: '2026-06-03',
        review: { comment: 'Спасибо за чистую и исправную кофемашину.', rating: 5, createdAt: '2026-06-04' },
      },
    ],
  },
  {
    name: 'Даниил Волков',
    joinedAt: '2023-02-19',
    avatarUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
    likes: 63,
    chatsCount: 36,
    views: [
      {
        title: 'Комплект колёс',
        category: 'Транспорт',
        subcategory: 'Запчасти',
        price: 84000,
        viewCount: 8,
        lastViewedAt: '2026-03-30T19:40:00',
        isFavorite: true,
        favoritedAt: '2026-03-22T09:30:00',
        isPurchased: true,
        purchasedAt: '2026-03-30T19:40:00',
      },
      {
        title: 'Видеорегистратор',
        category: 'Транспорт',
        subcategory: 'Автоэлектроника',
        price: 15400,
        viewCount: 6,
        lastViewedAt: '2026-06-11T12:20:00',
        isFavorite: false,
        isPurchased: true,
        purchasedAt: '2026-06-11T12:20:00',
      },
      {
        title: 'Держатель для телефона',
        category: 'Транспорт',
        subcategory: 'Автоаксессуары',
        price: 990,
        viewCount: 4,
        lastViewedAt: '2026-01-24T11:55:00',
        isFavorite: false,
        isPurchased: true,
        purchasedAt: '2026-01-24T11:55:00',
      },
    ],
    ownAds: [
      {
        title: 'Горный велосипед',
        category: 'Хобби и отдых',
        subcategory: 'Спорт',
        price: 46800,
        viewCount: 302,
        isArchived: true,
        isSold: true,
        soldAt: '2026-04-16',
        review: { comment: 'Велосипед соответствует описанию, продавца рекомендую.', rating: 5, createdAt: '2026-04-17' },
      },
      {
        title: 'Автомагнитола',
        category: 'Транспорт',
        subcategory: 'Автоэлектроника',
        price: 9400,
        viewCount: 117,
        isArchived: true,
        isSold: true,
        soldAt: '2026-05-08',
      },
    ],
  },
]

export const TEST_PROFILES: GetProfilesResponse = TEST_PROFILE_CREATE_REQUESTS.map(createMockProfileResponse)
